version: "2"
services:
  redis-cluster:
    image: grokzen/redis-cluster:latest
    environment:
      IP: "0.0.0.0"
      # SENTINEL: ${REDIS_USE_SENTINEL}
      # STANDALONE: ${REDIS_USE_STANDALONE}
    ports:
      - "7000-7050:7000-7050"
      - "5000-5010:5000-5010"
