version: "3"

services:
  loki:
    image: grafana/loki:2.3.0
    restart: "always"
    ports:
      - "3100:3100"
    volumes:
      - "./loki-local-config.yaml:/etc/loki/local-config.yaml"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.3.0
    restart: "always"
    volumes:
      - ./promtail_log:/var/log
      - ./promtail-local-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"

networks:
  default:
    external:
      name: monitor-bridge-network
