version: "3"
services:
  jaeger:
    image: "jaegertracing/all-in-one:1.19"
    ports:
      # accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
      - "5775:5775/udp"
      # accept jaeger.thrift over compact thrift protocol
      - "6831:6831/udp"
      # accept jaeger.thrift over binary thrift protocol
      - "6832:6832/udp"
      # serve configs
      - "5778:5778"
      # serve frontend
      - "16686:16686"
      # accept jaeger.thrift directly from clients
      - "14268:14268"
      # accept model.proto
      - "14250:14250"
      # Zipkin compatible endpoint (optional)
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
