version: "3"
services:
  prometheus:
    restart: "always"
    # network_mode: host
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - default
networks:
  default:
    external:
      name: monitor-bridge-network
