version: "3"
services:
  grafana:
    image: grafana/grafana:8.1.6
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "13000:3000"
    # network_mode: host
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
      - ./grafana.ini:/etc/grafana/grafana.ini
networks:
  default:
    external:
      name: monitor-bridge-network
