x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "10m"
      labels-regex: "^.+"

x-network: &default-network
  networks:
    - internal-prod

x-commons: &default-commons
  <<: [*default-logging, *default-network]
  restart: always

volumes:
    grafana_data: {}

services:
  grafana:
    <<: *default-commons
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_SECURITY_ADMIN_USER=
      - GF_SECURITY_ADMIN_PASSWORD=
    ports:
      - "13000:3000"
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/dashboards:/var/lib/grafana/dashboards
      - ./config/datasources:/etc/grafana/datasources
      - grafana_data:/var/lib/grafana

networks:
  internal-prod:
    name: prod_backend
    external: true
    
