version: "3.1"

services:
  db:
    image: mysql:5.7
    container_name: mysql_local
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: localtest
      MYSQL_PASSWORD: localtest
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: localpassword
