version: '3'
services:
  kong-database:
    restart: on-failure
    image: postgres:9.5
    ports:
      -  '5432:5432'
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=your_pwd
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    # win10 error occur
    # volumes:
    #   - ./kong_data:/var/lib/postgresql/data
  kong-migrations:
    image: kong
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: your_pwd
      KONG_PG_USER: kong
    links:
      - kong-database
    restart: on-failure
  web:
    restart: on-failure
    image: kong
    ports:
      - "8000:8000"
      - "8442:8443"
      - "8001:8001"
      - "8444:8444"
    links:
      - kong-database
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=your_pwd
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
  ui:
    restart: on-failure
    image: pantsel/konga
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=c885e895-5dd9-4e72-8244-b0037497cff6
      # - DB_ADAPTER=postgres
      # - DB_HOST=konga-database
      # - DB_PORT=5433
      # - DB_USER=konga
      # - DB_PASSWORD=your_pwd
    # links:
    #   - konga-database
    depends_on:
      - web
      # - konga-database
  # konga-database:
  #   restart: on-failure
  #   image: postgres:9.5
  #   ports:
  #     -  '5433:5433'
  #   environment:
  #     - POSTGRES_DB=konga
  #     - POSTGRES_USER=konga
  #     - POSTGRES_PASSWORD=your_pwd
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3